# Generated by Django 4.2.3 on 2024-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
