# Generated by Django 4.2.3 on 2024-04-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buddy_request_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('fromUser', 'toUser')},
        ),
    ]
