# Generated by Django 4.2.3 on 2024-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_request_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buddy',
            unique_together={('user1', 'user2')},
        ),
    ]
