# Generated by Django 4.2.3 on 2024-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_buddy_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='mobile',
            new_name='phone',
        ),
    ]
